#ifndef INSTRUCTION_TABLES_H
#define INSTRUCTION_TABLES_H

#include "cpu.h"

#include <cstdint>
#include <utility>

enum class AddressMode: uint8_t {
  Absolute,
  AbsoluteX,
  AbsoluteY,
  Accumulator,  // Might be behave identically to implicit
  Immediate,
  Implied,
  Indirect,
  IndirectX,
  IndirectY,
  Relative,
  ZeroPage,
  ZeroPageX,
  ZeroPageY,
  NotSupported
};

enum class Operation: uint8_t {
  ADC,  // And with carry
  AND,  // And (with accumulator)
  ASL,  // Arithmetic shift left
  BCC,  // Branch on carry clear
  BCS,  // Branch on carry set
  BEQ,  // Branch on equal (zero set)
  BIT,  // Bit test
  BMI,  // Branch on minus (negative set)
  BNE,  // Branch on not equal (zero clear)
  BPL,  // Branch on plus (negative clear)
  BRK,  // Break / interrupt
  BVC,  // Branch on overflow clear
  BVS,  // Branch on overflow set
  CLC,  // Clear carry
  CLD,  // Clear decimal
  CLI,  // Clear interrupt disable
  CLV,  // Clear overflow
  CMP,  // Compare (with accumulator)
  CPX,  // Compare with X
  CPY,  // Compare with Y
  DEC,  // Decrement
  DEX,  // Decrement X
  DEY,  // Decrement Y
  EOR,  // Exclusive or (with accumulator)
  INC,  // Increment
  INX,  // Increment X
  INY,  // Increment Y
  JMP,  // Jump
  JSR,  // Jump subroutine
  LDA,  // Load accumulator
  LDX,  // Load X
  LDY,  // Load Y
  LSR,  // Logical shift right
  NOP,  // No operation
  ORA,  // Or with accumulator
  PHA,  // Push accumulator
  PHP,  // Push processor status (SR)
  PLA,  // Pull accumulator
  PLP,  // Pull processor status (SR)
  ROL,  // Rotate left
  ROR,  // Rotate right
  RTI,  // Return from interrupt
  RTS,  // Return from subroutine
  SBC,  // Subtract with carry
  SEC,  // Set carry
  SED,  // Set decimal
  SEI,  // Set interrupt disable
  STA,  // Set accumulator
  STX,  // Store X
  STY,  // Store Y
  TAX,  // Transfer accumulator to X
  TAY,  // Transfer accumulator to Y
  TSX,  // Transfer stack ponter to X
  TXA,  // Transfer X to accumulator
  TXS,  // Transfer X to stack pointer
  TYA,  // Transfer Y to accumulator
  NotSupported,
};

const std::pair<AddressMode, Operation> instruction_lookup[256] = {
  {AddressMode::Implied, Operation::BRK},
  {AddressMode::Relative, Operation::BPL},
  {AddressMode::Absolute, Operation::JSR},
  {AddressMode::Relative, Operation::RTI},
  {AddressMode::Implied, Operation::BMI},
  {AddressMode::Relative, Operation::RTI},
  {AddressMode::Implied, Operation::BVC},
  {AddressMode::Relative, Operation::BVS},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Relative, Operation::BCC},
  {AddressMode::Immediate, Operation::LDY},
  {AddressMode::Relative, Operation::BCS},
  {AddressMode::Immediate, Operation::CPY},
  {AddressMode::Relative, Operation::BNE},
  {AddressMode::Immediate, Operation::CPX},
  {AddressMode::Relative, Operation::BEQ},
  {AddressMode::IndirectX, Operation::ORA},
  {AddressMode::IndirectY, Operation::ORA},
  {AddressMode::IndirectX, Operation::AND},
  {AddressMode::IndirectY, Operation::AND},
  {AddressMode::IndirectX, Operation::EOR},
  {AddressMode::IndirectY, Operation::EOR},
  {AddressMode::IndirectX, Operation::ADC},
  {AddressMode::IndirectY, Operation::ADC},
  {AddressMode::IndirectX, Operation::STA},
  {AddressMode::IndirectY, Operation::STA},
  {AddressMode::IndirectX, Operation::LDA},
  {AddressMode::IndirectY, Operation::LDA},
  {AddressMode::IndirectX, Operation::CMP},
  {AddressMode::IndirectY, Operation::CMP},
  {AddressMode::IndirectX, Operation::SBC},
  {AddressMode::IndirectY, Operation::SBC},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Immediate, Operation::LDX},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::ZeroPage, Operation::BIT},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::ZeroPage, Operation::STY},
  {AddressMode::ZeroPageX, Operation::STY},
  {AddressMode::ZeroPage, Operation::LDY},
  {AddressMode::ZeroPageX, Operation::LDY},
  {AddressMode::ZeroPage, Operation::CPY},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::ZeroPage, Operation::CPX},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::ZeroPage, Operation::ORA},
  {AddressMode::ZeroPageX, Operation::ORA},
  {AddressMode::ZeroPage, Operation::AND},
  {AddressMode::ZeroPageX, Operation::AND},
  {AddressMode::ZeroPage, Operation::EOR},
  {AddressMode::ZeroPageX, Operation::EOR},
  {AddressMode::ZeroPage, Operation::ADC},
  {AddressMode::ZeroPageX, Operation::ADC},
  {AddressMode::ZeroPage, Operation::STA},
  {AddressMode::ZeroPageX, Operation::STA},
  {AddressMode::ZeroPage, Operation::LDA},
  {AddressMode::ZeroPageX, Operation::LDA},
  {AddressMode::ZeroPage, Operation::CMP},
  {AddressMode::ZeroPageX, Operation::CMP},
  {AddressMode::ZeroPage, Operation::SBC},
  {AddressMode::ZeroPageX, Operation::SBC},
  {AddressMode::ZeroPage, Operation::ASL},
  {AddressMode::ZeroPageX, Operation::ASL},
  {AddressMode::ZeroPage, Operation::ROL},
  {AddressMode::ZeroPageX, Operation::ROL},
  {AddressMode::ZeroPage, Operation::LSR},
  {AddressMode::ZeroPageX, Operation::LSR},
  {AddressMode::ZeroPage, Operation::ROR},
  {AddressMode::ZeroPageX, Operation::ROR},
  {AddressMode::ZeroPage, Operation::STX},
  {AddressMode::ZeroPageX, Operation::STX},
  {AddressMode::ZeroPage, Operation::LDX},
  {AddressMode::ZeroPageX, Operation::LDX},
  {AddressMode::ZeroPage, Operation::DEC},
  {AddressMode::ZeroPageX, Operation::DEC},
  {AddressMode::ZeroPage, Operation::INC},
  {AddressMode::ZeroPageX, Operation::INC},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Implied, Operation::PHP},
  {AddressMode::Implied, Operation::CLC},
  {AddressMode::Implied, Operation::PLP},
  {AddressMode::Implied, Operation::SEC},
  {AddressMode::Implied, Operation::PHA},
  {AddressMode::Implied, Operation::CLI},
  {AddressMode::Implied, Operation::PLA},
  {AddressMode::Implied, Operation::SEI},
  {AddressMode::Implied, Operation::DEY},
  {AddressMode::Implied, Operation::TYA},
  {AddressMode::Implied, Operation::TAY},
  {AddressMode::Implied, Operation::CLV},
  {AddressMode::Implied, Operation::INY},
  {AddressMode::Implied, Operation::CLD},
  {AddressMode::Implied, Operation::INX},
  {AddressMode::Implied, Operation::SED},
  {AddressMode::Immediate, Operation::ORA},
  {AddressMode::AbsoluteY, Operation::ORA},
  {AddressMode::Immediate, Operation::AND},
  {AddressMode::AbsoluteY, Operation::AND},
  {AddressMode::Immediate, Operation::EOR},
  {AddressMode::AbsoluteY, Operation::EOR},
  {AddressMode::Immediate, Operation::ADC},
  {AddressMode::AbsoluteY, Operation::ADC},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::AbsoluteY, Operation::STA},
  {AddressMode::Immediate, Operation::LDA},
  {AddressMode::AbsoluteY, Operation::LDA},
  {AddressMode::Immediate, Operation::CMP},
  {AddressMode::AbsoluteY, Operation::CMP},
  {AddressMode::Immediate, Operation::SBC},
  {AddressMode::AbsoluteY, Operation::SBC},
  {AddressMode::Accumulator, Operation::ASL},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Accumulator, Operation::ROL},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Accumulator, Operation::LSR},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Accumulator, Operation::ROR},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Implied, Operation::TXA},
  {AddressMode::Implied, Operation::TXS},
  {AddressMode::Implied, Operation::TAX},
  {AddressMode::Implied, Operation::TSX},
  {AddressMode::Implied, Operation::DEX},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Implied, Operation::NOP},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Absolute, Operation::BIT},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Absolute, Operation::JMP},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Indirect, Operation::JMP},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Absolute, Operation::STY},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Absolute, Operation::LDY},
  {AddressMode::AbsoluteX, Operation::LDY},
  {AddressMode::Absolute, Operation::CPY},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Absolute, Operation::CPX},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Absolute, Operation::ORA},
  {AddressMode::AbsoluteX, Operation::ORA},
  {AddressMode::Absolute, Operation::AND},
  {AddressMode::AbsoluteX, Operation::AND},
  {AddressMode::Absolute, Operation::EOR},
  {AddressMode::AbsoluteX, Operation::EOR},
  {AddressMode::Absolute, Operation::ADC},
  {AddressMode::AbsoluteX, Operation::ADC},
  {AddressMode::Absolute, Operation::STA},
  {AddressMode::AbsoluteX, Operation::STA},
  {AddressMode::Absolute, Operation::LDA},
  {AddressMode::AbsoluteX, Operation::LDA},
  {AddressMode::Absolute, Operation::CMP},
  {AddressMode::AbsoluteX, Operation::CMP},
  {AddressMode::Absolute, Operation::SBC},
  {AddressMode::AbsoluteX, Operation::SBC},
  {AddressMode::Absolute, Operation::ASL},
  {AddressMode::AbsoluteY, Operation::ASL},
  {AddressMode::Absolute, Operation::ROL},
  {AddressMode::AbsoluteY, Operation::ROL},
  {AddressMode::Absolute, Operation::LSR},
  {AddressMode::AbsoluteY, Operation::LSR},
  {AddressMode::Absolute, Operation::ROR},
  {AddressMode::AbsoluteY, Operation::ROR},
  {AddressMode::Absolute, Operation::STX},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::Absolute, Operation::LDX},
  {AddressMode::AbsoluteY, Operation::LDX},
  {AddressMode::Absolute, Operation::DEC},
  {AddressMode::AbsoluteY, Operation::DEC},
  {AddressMode::Absolute, Operation::INC},
  {AddressMode::AbsoluteY, Operation::INC},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
  {AddressMode::NotSupported, Operation::NotSupported},
};

std::optional<uint16_t> (CPU::*address_mode_lookup[13])() = {
  &CPU::addressing_absolute,
  &CPU::addressing_absoluteX,
  &CPU::addressing_absoluteY,
  &CPU::addressing_accumulator,
  &CPU::addressing_immediate,
  &CPU::addressing_implied,
  &CPU::addressing_indirect,
  &CPU::addressing_indirectX,
  &CPU::addressing_indirectY,
  &CPU::addressing_relative,
  &CPU::addressing_zeropage,
  &CPU::addressing_zeropageX,
  &CPU::addressing_zeropageY,
};

void (CPU::*operation_lookup[56])(std::optional<uint16_t>) = {
&CPU::ADC,
&CPU::AND,
&CPU::ASL,
&CPU::BCC,
&CPU::BCS,
&CPU::BEQ,
&CPU::BIT,
&CPU::BMI,
&CPU::BNE,
&CPU::BPL,
&CPU::BRK,
&CPU::BVC,
&CPU::BVS,
&CPU::CLC,
&CPU::CLD,
&CPU::CLI,
&CPU::CLV,
&CPU::CMP,
&CPU::CPX,
&CPU::CPY,
&CPU::DEC,
&CPU::DEX,
&CPU::DEY,
&CPU::EOR,
&CPU::INC,
&CPU::INX,
&CPU::INY,
&CPU::JMP,
&CPU::JSR,
&CPU::LDA,
&CPU::LDX,
&CPU::LDY,
&CPU::LSR,
&CPU::NOP,
&CPU::ORA,
&CPU::PHA,
&CPU::PHP,
&CPU::PLA,
&CPU::PLP,
&CPU::ROL,
&CPU::ROR,
&CPU::RTI,
&CPU::RTS,
&CPU::SBC,
&CPU::SEC,
&CPU::SED,
&CPU::SEI,
&CPU::STA,
&CPU::STX,
&CPU::STY,
&CPU::TAX,
&CPU::TAY,
&CPU::TSX,
&CPU::TXA,
&CPU::TXS,
&CPU::TYA,
};

#endif  // INSTRUCTION_TABLES_H
